### ISSUE TITLE
No TypeScript declaration file

### ISSUE THREAD

**Issue by gdude2002** [hCaptcha/vue-hcaptcha#1]
Attempting to make use of this module in a TypeScript environment (using Webpack here, but probably in other environments too) raises an error.

```typescript
import Vue from "vue"
import VueHcaptcha from "@hcaptcha/vue-hcaptcha"

// ...

Vue.component("vue-hcaptcha", VueHcaptcha)
```

Gives...

```
ERROR in C:\Users\coles\IdeaProjects\Recipes\assets\ts\app.ts
./assets/ts/app.ts
[tsl] ERROR in C:\Users\coles\IdeaProjects\Recipes\assets\ts\app.ts(12,25)
      TS7016: Could not find a declaration file for module '@hcaptcha/vue-hcaptcha'. 'C:\Users\coles\IdeaProjects\Recipes\node_modules\@hcaptcha\vue-hcaptcha\src\main.js' implicitly has an 'any' type.
```

**Comment by gdude2002** [comment]
For users currently dealing with this problem: You can work around it by creating a dummy TypeScript declaration file. For example, in `hcaptcha.d.ts`:

```typescript
declare module "@hcaptcha/vue-hcaptcha"
```

**Comment by e271828-** [comment]
@gdude2002 if you end up filling this out, please submit to DefinitelyTyped.

**Comment by geopic** [comment]
I'll get started on this and submit it to DT @gdude2002 @e271828-.

**Comment by gdude2002** [comment]
Thanks @geopic, I haven't had time to look into it

**Comment by geopic** [comment]
Submitted it to DT (https://github.com/DefinitelyTyped/DefinitelyTyped/pull/44299) but it looks like there are some issues so I'll look at it again tomorrow.
