### ISSUE TITLE
Define vue as a peerDependency

### ISSUE THREAD

**Issue by DispatchCommit** [hCaptcha/vue-hcaptcha#19]
Copied from comment here: https://github.com/hCaptcha/vue-hcaptcha/pull/18#pullrequestreview-483153892

define vue as a peerDependency to indicate that major version >= 2 < 3 is expected to be installed by consuming project:

```js
"peerDependencies": {
    "vue": "^2.0.0"
 }
```

**Comment by DSergiu** [comment]
Thank you for pointing it out. It will be deployed with the next release.
