### ISSUE TITLE
publish 0.2.3 to npm

### ISSUE THREAD

**Issue by e271828-** [hCaptcha/vue-hcaptcha#20]

**Comment by xelyos94ro** [comment]
up!

**Comment by levz0r** [comment]
Please. Looking forward to the `language` prop.

**Comment by xelyos94ro** [comment]
in version 0.2.2 prop language not exists. whwn we use npm/yarn install the package is downloaded from npm repo, and there the version is 0.2.2

**Comment by e271828-** [comment]
https://www.npmjs.com/package/@hcaptcha/vue-hcaptcha/v/0.2.3 now live.
