### ISSUE TITLE
unexpected token '<' error

### ISSUE THREAD

**Issue by c-myers1** [hCaptcha/vue-hcaptcha#21]
I'm using vue-hcaptcha with Nuxt and get this error. Following is the whole CLI dialog:

    $ yarn dev
    yarn run v1.17.3
    $ nuxt
    i Merging Tailwind config from ~/tailwind.config.js                                                                                                                  
    nuxt:tailwindcss 19:10:54
    
     FATAL  Unexpected token '<'                                                                                                                                                          
    19:10:54
    
      <template>
      ^
    
      SyntaxError: Unexpected token '<'
      at Object.compileFunction (vm.js:376:18)
      at Generator.next (<anonymous>)
      at Object.<anonymous> (node_modules\@hcaptcha\vue-hcaptcha\src\main.js:1)
      at Generator.next (<anonymous>)
    

       ╭───────────────────────────────────────╮
       │                                       │
       │   ✖ Nuxt Fatal Error                  │
       │                                       │
       │   SyntaxError: Unexpected token '<'   │
       │                                       │
       ╰───────────────────────────────────────╯
    
    error Command failed with exit code 1.
    info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
`
Once I comment out '@hcaptcha/vue-hcaptcha' in modules, nuxt.config.js, my code recompiles but of course hcaptcha doesnt work.

When I put the following in head section of nuxt.config.js and then div in template, it shows on screen. However, I have no way of accessing the generated token for verification since I'm sending my POST request with axios.

`script: [{
            src: 'https://hcaptcha.com/1/api.js'
        }]`

How can I resolve this?

**Comment by e271828-** [comment]
That seems like a download is breaking, and you're getting HTML or similar. Did you inspect the JS manually?

**Comment by c-myers1** [comment]
How do I go about that? Would that mean I need to modify the core hcaptcha files? Very scary for me, I'm a back-ender who just gets by on front-end stuff. :-)
