### ISSUE TITLE
How to create an invisible captcha?

### ISSUE THREAD

**Issue by pedr0-fr** [hCaptcha/vue-hcaptcha#37]
Can you add an example on how to use an invible hcaptcha associated to a button?

Is it supposed to be something like:

`<button><vue-hcaptcha sitekey="**Your sitekey here**" size="invisible"></vue-hcaptcha><button>`

**Comment by e271828-** [comment]
Hi, this is in the example:

https://github.com/hCaptcha/vue-hcaptcha/blob/71d5a4a5bf2200be516961a3c8cbd46704e78528/examples/traditional-vue-app/src/App.vue#L38
