### ISSUE TITLE
Using the "interests" parameter

### ISSUE THREAD

**Issue by zaharr2** [hCaptcha/vue-hcaptcha#38]
Can we use and how this parameter?
https://docs.hcaptcha.com/api#table-of-interests

**Comment by brdlyptrs** [comment]
Hi @zaharr2 that is part of the sitkey configuration setting which is separate from the hCaptcha JS API.  You can see this setting when logging into your hCaptcha dashboard account and viewing any site / sitekey created, see screenshot below.

![image.png](https://images.zenhubusercontent.com/5b80883c22e474383b9846bc/df05c7c1-d63f-4145-ad2e-83c9edd68f9c)
