### ISSUE TITLE
Credit for my changes with Vue 3 support

### ISSUE THREAD

**Issue by JDinABox** [hCaptcha/vue-hcaptcha#46]
I would like to know why I was not given credit for the changes that were adopted in PR #41 (see #40 for my PR).
@brdlyptrs mentioned #40 in #41 also. 

Thanks,
JDinABox

**Comment by DSergiu** [comment]
Yes. I ended up doing it from scratch as more fundamental changes were needed such as:
* switching to a monorepo with lerna
* updating ci/cd pipeline
* adding vue3 package which reuses the component from vue2 but bundles it for vue3 with adjusted vite generated config 
* adding vue3 tests: unit and integration
* adding vue3 examples: traditional app and script usage
* updating README

**Comment by JDinABox** [comment]
@e271828- Thanks for the reply.

@DSergiu Looking at [packages/vue3](https://github.com/hCaptcha/vue-hcaptcha/blob/master/packages/vue3) many of the new files appear to be almost identical to the one's in [JDinABox/vue-3-hcaptcha](https://github.com/JDinABox/vue-3-hcaptcha) (of which master is identical to #40) which you claim to have, "ended up doing it from scratch".

The many of modifications I made to [examples/traditional-vue-app](https://github.com/JDinABox/vue-3-hcaptcha/tree/master/examples/traditional-vue-app) have also been copied, with little (if any) modification, to [examples/traditional-vue3](https://github.com/hCaptcha/vue-hcaptcha/tree/master/examples/traditional-vue3)

#### See the following examples:

#### [JDinABox/vue-3-hcaptcha](https://github.com/JDinABox/vue-3-hcaptcha) vs [hCaptcha/vue-hcaptcha/packages/vue3](https://github.com/hCaptcha/vue-hcaptcha/tree/master/packages/vue3):

- [vite.config.js](https://github.com/JDinABox/vue-3-hcaptcha/blob/master/vite.config.js) -> [vue3/vite.config.js](https://github.com/hCaptcha/vue-hcaptcha/tree/master/packages/vue3/vite.config.js)
- [jest.config.js](https://github.com/JDinABox/vue-3-hcaptcha/blob/master/jest.config.js) -> [vue3/jest.config.js](https://github.com/hCaptcha/vue-hcaptcha/tree/master/packages/vue3/jest.config.js)

#### [JDinABox/vue-3-hcaptcha/examples/traditional-vue-app](https://github.com/JDinABox/vue-3-hcaptcha/blob/master/examples/traditional-vue-app) vs [hCaptcha/vue-hcaptcha/examples/traditional-vue3](https://github.com/hCaptcha/vue-hcaptcha/blob/master/examples/traditional-vue3)

- [src/main.js](https://github.com/JDinABox/vue-3-hcaptcha/blob/master/examples/traditional-vue-app/src/main.js) -> [traditional-vue3/src/main.js](https://github.com/hCaptcha/vue-hcaptcha/blob/master/examples/traditional-vue3/src/main.js)
- [index.html](https://github.com/JDinABox/vue-3-hcaptcha/blob/master/examples/traditional-vue-app/index.html) -> [traditional-vue3/index.html](https://github.com/hCaptcha/vue-hcaptcha/blob/master/examples/traditional-vue3/index.html)
- [vite.config.js](https://github.com/JDinABox/vue-3-hcaptcha/blob/master/examples/traditional-vue-app/vite.config.js) -> [traditional-vue3/vite.config.js](https://github.com/hCaptcha/vue-hcaptcha/blob/master/examples/traditional-vue3/vite.config.js)

I won't deny you made many changes I didn't in #41, I would just like credit for my changes.

\- JD

**Comment by JDinABox** [comment]
Thanks @e271828-
