### ISSUE TITLE
Note: There's a known flaw when there are multiple captchas being rendered. It's recommended to use only one captcha per page.

### ISSUE THREAD

**Issue by Aralun** [hCaptcha/vue-hcaptcha#5]
The README says:

> Note: There's a known flaw when there are multiple captchas being rendered. It's recommended to use only one captcha per page.

What is this flaw exactly?

**Comment by e271828-** [comment]
That may be out of date, worth trying it out.

**Comment by DSergiu** [comment]
Issue still persists and is in main js (https://hcaptcha.com/1/api.js?render=explicit) and not in this repo.
