### ISSUE TITLE
Vue3 version is missing TypeScript declarations

### ISSUE THREAD

**Issue by shubhamranjan** [hCaptcha/vue-hcaptcha#50]
The [vue3 version](https://www.npmjs.com/package/@hcaptcha/vue3-hcaptcha) seems to be missing the TypeScript declarations which the [vue2 version](https://www.npmjs.com/package/@hcaptcha/vue-hcaptcha) has

**Comment by hgouveia** [comment]
facing the same issue

**Comment by cindrmon** [comment]
I'm sorry for this comment, but I'm also having the same issue. The `README.md` lacks a very detailed description with their `TypeScript` section, and all they show is them saying that:
> ### TypeScript
> TypeScript is supported (`types/index.d.ts`), and you can see an example by running `npm run serve:ts`.

without any further explanation whatsoever. 

The only example they gave out with typescript is with vue 2. And I don't think they have that exact same configuration for vue 3 yet, as far as I know.

I just hope they update that section as well.

**Comment by shubhamranjan** [comment]
Ported a version for my use case until this is resolved.

Ref: https://github.com/shubhamranjan/vue-hcaptcha

**Comment by e271828-** [comment]
@shubhamranjan PRs welcome to this repo as well.

**Comment by SKFrozenCloud** [comment]
The vue3 package seems to be just the vue2 package wrapped, so technically you could just use the vue2 package and everything would be the same.

The vue3 example imports the vue2 package:
https://github.com/hCaptcha/vue-hcaptcha/blob/master/examples/traditional-vue3/src/App.vue

**Comment by lbineau** [comment]
Any news on that topic? We have an enterprise plan for hCaptcha but we are not able to use the Vue 3 component because it is not compatible with typescript...

**Comment by danchernov-js** [comment]
big problem

**Comment by DSergiu** [comment]
Hey. Thank you for reporting this. Types were added to `@hcaptcha/vue3-hcaptcha@1.2.1`. 

Closing this, feel free to open a new ticket if necessary.
