### ISSUE TITLE
Unexpected behaviours on local environment

### ISSUE THREAD

**Issue by Llois41** [hCaptcha/vue-hcaptcha#52]
I'm experiencing some strange issues trying to implement hCaptcha in my vue appliation.

## Scenario 1 - Using `localhost` as host
- call to `hcaptcha.com/checksiteconfig?...` returns 403 due to missing CORS headers on requested resource
- after that it calls `api.hcaptcha.com/checksiteconfig?...` and succeeds with 200
- after checking the "i'm human" checkbox, the challenge is requested from `api.hcaptcha.com/getcaptcha?...` and returns a solveable captcha.

## Scenario 2 - Using `127.0.0.1` or in [documentation suggested host entry](https://docs.hcaptcha.com/#local-development) as host
- call to `hcaptcha.com/checksiteconfig?...` returns 200
- after checking the "i'm human" checkbox, the challenge is requested from `hcaptcha.com/getcaptcha?...` but it returns a token (but no eKey?) without solving a captcha.

I'm sure the last one's kind of a feature but not sure why these scenarios differ in their outcome, while the only diffenrences I can see are by calling either `api.hcaptcha.com` or `hcaptcha.com`.

Don't know if this is an issue or limited to vue but I didn't found anything in the docs and it confuses me.

**Comment by brdlyptrs** [comment]
Hi @Llois41 the first scenario presented is the correct behavior, the second scenario sounds correct as well if you are using the testing keys as described in the documentation.
