### ISSUE TITLE
No Secret Key capabilities

### ISSUE THREAD

**Issue by SoapyFresh** [hCaptcha/vue-hcaptcha#6]
This middleware works beautifully with the sitekey to determine if the captcha is valid.  How do we implement this with our secret key to get credit when we validate the hcaptcha server-side?

**Comment by DSergiu** [comment]
Frontend: 
1. show captcha based on your siteKey
2. solve captcha, get validation token and send to backend

Backend:
1. verify validation token using your linked secret key 
(credit is added automatically upon success)

e.g. `curl -d "response=CLIENT-RESPONSE&secret=YOUR-SECRET" -X POST https://hcaptcha.com/siteverify`

See https://docs.hcaptcha.com

**Comment by e271828-** [comment]
Yes, this is out of scope for a vue addon: your server needs to do that part.
