### ISSUE TITLE
error 401

### ISSUE THREAD

**Issue by Heartz66** [hCaptcha/vue-hcaptcha#61]
Captchas by hCaptcha have randomly stopped working. I have tested several browsers and it keeps throwing the error. Other people are experiencing the same issue. The following error is visible in the Chrome developer console:

`GET https://hcaptcha.com/1/api.js?render=explicit&onload=_hcaptchaOnLoad&sentry=true net::ERR_ABORTED 401`
`Failed to load api: https://hcaptcha.com/1/api.js?render=explicit&onload=_hcaptchaOnLoad&sentry=true Event {isTrusted: true, type: 'error', target: script#hcaptcha-api-script-id, currentTarget: script#hcaptcha-api-script-id, eventPhase: 2, …}`

**Comment by e271828-** [comment]
Closing: not a code issue.
