### ISSUE TITLE
Error: Unable to preventDefault inside passive event listener invocation.

### ISSUE THREAD

**Issue by vsmartcode** [hCaptcha/vue-hcaptcha#73]
I am getting the following error but don't know how to solve it, please help!
![image](https://user-images.githubusercontent.com/4949809/186573425-85078b6f-61b3-499f-9835-697e3448b63f.png)

**Comment by brdlyptrs** [comment]
Hi @vsmartcode, are using using event.preventDefault() anywhere or setting an [event listener as passive](https://developer.mozilla.org/en-US/docs/Web/API/EventTarget/addEventListener#parameters)?

**Comment by vsmartcode** [comment]
![image](https://user-images.githubusercontent.com/4949809/186575970-39be181e-e3c3-4ef9-a70c-2deed78c537e.png)
Thank @brdlyptrs !
it is true that i use event.preventDefault() to delay the submission when the user clicks the button.

**Comment by brdlyptrs** [comment]
@vsmartcode shall we close or do you still need assistance?

**Comment by DSergiu** [comment]
Closing stale issue. Please reopen if necessary.
