### ISSUE TITLE
onError not work fine

### ISSUE THREAD

**Issue by aleffff** [hCaptcha/vue-hcaptcha#8]
If i send response of **@verify** to server and the server return bad request. 

How to restore the component?

**Comment by DSergiu** [comment]
You can restore the component by calling `reset()` method.

**Comment by woolfi20** [comment]
> You can restore the component by calling `reset()` method.

how i can reset ? Can u send example because this doesn't work https://i.imgur.com/mUkVytT.png

**Comment by woolfi20** [comment]
And VueHcaptcha.reset(); doesn't work :(

**Comment by DSergiu** [comment]
You need to call `reset` on the component itself. One way is by adding a [reference](https://vuejs.org/v2/api/#ref):
```vue
 <vue-hcaptcha
            ref="invisibleHcaptcha"
            sitekey="10000000-ffff-ffff-ffff-000000000001"
            size="invisible"
           ...
        />
```

And in code you can call reset this way:
```vue
this.$refs.invisibleHcaptcha.execute()
```

**Comment by brdlyptrs** [comment]
Closing as @DSergiu's answer should be the correct answer.
