### ISSUE TITLE
Support for async execute

### ISSUE THREAD

**Issue by lbineau** [hCaptcha/vue-hcaptcha#81]
According to hCaptcha documentation `execute` function is supposed to be able to be asynchronous (returns a Promise) https://docs.hcaptcha.com/configuration/#asynchronous-mode

I see no way to have the same behavior on the vue component: https://github.com/hCaptcha/vue-hcaptcha/blob/master/packages/vue2/src/hcaptcha.vue#L114

It would be good to be able to use it because it will help to be used with validation libraries (VeeValidate for instance)

**Comment by DSergiu** [comment]
There is now a [new method `executeAsync`](https://github.com/hCaptcha/vue-hcaptcha#methods) which returns a promise.

New versions: `@hcaptcha/vue-hcaptcha@0.4.0` and `@hcaptcha/vue3-hcaptcha@1.1.0`.
