### ISSUE TITLE
GitHub releases correspond to NPM releases?

### ISSUE THREAD

**Issue by ydnar** [hCaptcha/vue-hcaptcha#88]
We spotted the new release of [@hcaptcha/vue3-hcaptcha](https://www.npmjs.com/package/@hcaptcha/vue3-hcaptcha) on NPM, but didn’t see a corresponding release on this repo.

If your NPM account had been compromised, this is what we’d expect to see. Any way you can tag and release on GitHub when cutting a new release for NPM?

Thanks!

**Comment by DSergiu** [comment]
Thank you for reporting this. 

We decided to remove the github releases so there are no further confusion about the version mismatch between npm and github. You can always check the version in [code](https://github.com/hCaptcha/vue-hcaptcha/blob/master/packages/vue3/package.json#L3) if that helps with any doubts.

We would welcome any PR to do automatic release in github after publishing to npm.
